host: localhost
port: 5522

flatfile:
    directory: /data


backends: # backends are queried sequentially, in order; you probably want to define cache sources before non-cache sources

-
    type: source
    backend: flatfile

-
    type: sink
    backend: flatfile
    cache: False
